### PR TITLE
Add missing llr2bitProb function to optic.utils

### PR DESCRIPTION
**Pull request by Hewei603**
## Problem

The current `main` branch cannot be imported. `optic/comm/modulation.py` imports `llr2bitProb` from `optic.utils`, but that function is not defined anywhere in the package:

```python
>>> from optic.comm.modulation import grayMapping
ImportError: cannot import name 'llr2bitProb' from 'optic.utils'
```

Since `optic.comm.modulation` is imported by `optic.comm.metrics`, `optic.models.tx`, `optic.dsp.equalization` and `optic.dsp.carrierRecovery`, this breaks essentially the whole library, including all the example notebooks.

The import was introduced in cee1ca6, but the function itself was never committed.

## What was expected

`llr2bitProb` is referenced in two places, both as `llr2bitProb(-llr)`:

- `softEstimator()` in `optic/comm/modulation.py`
- `calcExtrLLR()` in `optic/comm/metrics.py`

`calcLLR()` produces LLRs following the `log(P(b=0)/P(b=1))` convention, so `Pb1 = llr2bitProb(-llr)` is consistent with the logistic function

```
llr2bitProb(x) = 1 / (1 + exp(-x))   =>   P(b=1) = 1 / (1 + exp(LLR))
```

## Changes

- Add `llr2bitProb()` to `optic/utils.py`, decorated with `@njit(cache=True)` so it can be called from the jitted `softEstimator()` and `calcExtrLLR()` routines, and list it in the module `autosummary`.
- Add the missing `llr2bitProb` import in `optic/comm/metrics.py`, where the function was used but never imported (which would raise a `NameError` in `calcExtrLLR()` even after the import error above is fixed).

## Verification

Tested on Python 3.14 with numpy 2.4.6 / scipy 1.18.0 / numba 0.66.0:

- All modules import correctly again.
- `pytest tests/` runs (`test_dsp.py` and `test_modulation.py` pass).
- End-to-end check with a single-channel PDM-16QAM coherent link (32 GBd, 400 km, `manakovSSF` + `pdmCoherentReceiver` + `edc` + `mimoAdaptEqualizer` + `cpr`) gives BER = 0, SNR ≈ 22.7 dB, GMI = 4.00 bits/symbol, as expected.

## Note (unrelated to this PR)

`tests/test_metrics.py::test_fastBERcalc` still fails, but for an independent reason: it calls `awgn(symbTx, snrdB)` passing a float where a `parameters` object is expected. Because `awgn()` reads its configuration with `getattr(param, "snr", 20)`, the SNR silently falls back to the 20 dB default and the measured BER no longer follows the swept `EbN0` values. I can open a separate PR/issue for that if you'd like.

## Summary by Sourcery

Restore importability and soft-metric computations by adding the missing LLR-to-bit-probability utility and wiring it into metrics.

New Features:
- Introduce llr2bitProb utility to convert log-likelihood ratios to bit probabilities.

Bug Fixes:
- Fix import errors across modulation and metrics modules by defining and importing the previously missing llr2bitProb function.

Enhancements:
- Document LLR conventions and usage notes for llr2bitProb in the utilities module.

### CODE REVIEW

**Comment by edsonportosilva** [comment]
Hello @Hewei603! Thanks for your warning! 

In fact, this issue was a result of a few changes and additions I have been doing in the repository this last week. The changes with `llr2bitProb` were already on the way, but not commited yet. I'm using a formulation that is more stable numerically than what you wrote. 

I have updated the repository now, so please check if all is fine. So, thanks, but the pull request won't be needed this time. However, if you want to update/check the tests, please feel free to do it. It would be really valuable. Unfortunatelly, I don't have time to write a better and more complete set of tests for the repository, although the examples folder kind of indireclty assumed this task  So, any help with this would be very welcome.

**Comment by Hewei603** [comment]
Thanks for the quick turnaround, and for explaining the context — I confirmed that `main` imports cleanly again, and your branchless-overflow version of the sigmoid is clearly the better formulation. Closing this one.

I would be glad to take up the tests. I opened #35 with a first pass: the failing `test_fastBERcalc` is fixed (it was passing a float to `awgn()`, so the SNR silently fell back to the 20 dB default), everything is ported to pytest, coverage is extended to `optic.utils`, `optic.dsp.core`, `optic.comm.modulation`, `optic.comm.metrics` and `optic.models.channels`, and there is a small GitHub Actions workflow so that an unusable `main` gets caught automatically.

A few things surfaced while writing the tests — a one-sample offset at the output of `edc()`, a `pnorm()` docstring that does not match its behaviour, `calcEVM()` returning the squared EVM, and two deprecated imports that SciPy and NumPy will eventually remove. They are all described at the end of the PR, and I left the code untouched. Happy to split any of them into their own issue or PR if you prefer.
